### ISSUE TITLE
Project request

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/puppet-verdaccio#1]
Hi, I'm one of the verdaccio maintainers and I saw your project is pretty well documented. I was wondering if you are interested to move it into the verdaccio organization, you will have more visibility and puppet + verdaccio users will find your project really fast. I asume you will be the main maintainer (I do not have a clue about puppet).

Are you interested?

**Comment by Dharmender-Singh** [comment]
Hi,
I am happy to migrate this project into the verdaccio organization. Please let me know, how we can achieve this.
Thanks & Regards
D.Singh

**Comment by juanpicado** [comment]
@Dharmender-Singh  cool !! I sent you and invitation. Feel free to move it. I'll grant you admin access in your repository and you will be the owner of it. Welcome aboard.

**Comment by Dharmender-Singh** [comment]
Hi,
I have done that. Please let me know, if anything else is require.

Looking forward to work with you guys :)

**Comment by juanpicado** [comment]
@Dharmender-Singh sure, at the moment I have a vague idea what puppet does, I'm learning. Perhaps you can tell what exactly what goals puppet + verdaccio you might have on mind.

**Comment by Dharmender-Singh** [comment]
@juanpicado : The main idea to create this module is to install the verdaccio and run as a service on Red Hat 7 Systems. I have configured the verdaccio for my organization using this module.  If you want to add some features then kindly let me know.

**Comment by juanpicado** [comment]
@Dharmender-Singh sure . I think with puppet I'm completely out of my field.  Let's wait someone needs something special. Thanks.

**Comment by Dharmender-Singh** [comment]
Sure @juanpicado . I am closing this thread now.  Thanks
