### ISSUE TITLE
Help contributors need it for Puppet 

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/puppet-verdaccio#11]
Lately, we are getting plenty of contributions in this repository, but, there isn't anybody with Puppet knowledge to maintain this project. 

It's anyone enough confident to take care of all PR in this project?
Until now I merge what I considere make sense, but, I mostly rely on PR descriptons.

What we need is someone/a group taking care of this repo actively.

**Comment by Dharmender-Singh** [comment]
@juanpicado  : Will do that, but it won't be quick. I can only check this repo in my evening.

**Comment by juanpicado** [comment]
Thanks @Dharmender-Singh . Any sort of help is very welcome.

**Comment by Dharmender-Singh** [comment]
@juanpicado  :  I have been removed as a collaborator on Verdaccio’s repositories.
![status](https://user-images.githubusercontent.com/12389415/43452146-a64c3e92-94ae-11e8-844f-a16aea606cdc.PNG)

Is that intentionally ?

**Comment by juanpicado** [comment]
@Dharmender-Singh my apologies, but I had to enable 2FA by default, some of members did it, others not. I did warn weeks ago about my intentions to enable it. Unfortunatelly GitHub did not allow me to keep members with 2FA disable. See my message:

<img width="791" alt="screen shot 2018-07-31 at 16 04 00" src="https://user-images.githubusercontent.com/558752/43464463-76d8347c-94db-11e8-9dd5-372355b19428.png">

My wish is to have as much members we can and provide them all roles they need to help grow this project, but for the other side, I'm the main responsable to keep this secure and nothing weird happens. 

Unfortunatelly, this clearly looks like I kicked you out of this project, but no, it's the oposite that I want. Since I have no direct channel with everybody and my unique channel is our internal board which seems not to visible for everybody.

I'd like to ask you to enable 2FA and then I'll be able to integrate you back again.
https://help.github.com/articles/accessing-github-using-two-factor-authentication/

Let me know whether you have any corcern about this. If you wish can join Discord to have a fluid communication.

http://chat.verdaccio.org

**Comment by Dharmender-Singh** [comment]
@juanpicado   :  I have enabled the 2FA factor.  Might be I missed this conversation. Could you please add me again. 
Thanks

**Comment by juanpicado** [comment]
Done

**Comment by Dharmender-Singh** [comment]
Thanks :)
